version: '3.7'

services:
  # ref: https://hub.docker.com/_/mariadb
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata:
