version: '3.7'

services:
  web:
    build: .
    ports:
      - 8080:8080
    entrypoint: "/bin/sh -c 'python /usr/src/database.py && python /usr/src/app.py'"
    volumes:
      - ./app:/usr/src
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: